apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::216444449243:role/eksctl-project4-cluster-nodegroup-NodeInstanceRole-1JID07EIVAOXT
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::216444449243:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-25T07:51:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3037"
  uid: 23fea407-d0a8-4c0c-bb84-7e37728bb262
